### ISSUE TITLE
Limited data availability through PN, MELS, MILS, BOD endpoints

### ISSUE THREAD

**Issue by trader-short** [elexon-data/insights-issues#19]
## Describe the issue
When you try to access data for any dates previous to 2022-07-09, the result is an empty response. The timeframe doesn't have to be large for the request to fail, just querying data for a single settlement period for these dates results in no data response. This is seen in most of the endpoints(also the stream).

## Steps to Reproduce
1. Go to /endpoint/datasets/PN or /endpoint/datasets/PN/stream
2. Select input parameters: 
      settlementDate - 2022-07-09 (or any date before)
      settlementPeriod -  5 (any)
4. See the empty data response

## Expected behaviour
Should return the PN data for the requested timeframe.
## Observed behaviour
No data 
## Screenshots
It is working fine till dates later than 2022-07-10
![capture-1](https://github.com/elexon-data/insights-issues/assets/56205818/33cf03ca-3c83-4271-942f-ae559050a718)

No data is received for the days past 2022-07-09
![Capture-2](https://github.com/elexon-data/insights-issues/assets/56205818/41ba2545-c167-48d0-93f4-c81931ae82f2)

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by zghanty** [comment]
@trader-short - Hi Zahid , we have task in the backlog to backfill historical data ETA November 2023.
