### ISSUE TITLE
API /balancing/physical endpoint returning 500

### ISSUE THREAD

**Issue by robin-leach** [elexon-data/insights-issues#2]
## Describe the issue
The [/balancing/physical](https://bmrs.elexon.co.uk/api-documentation/endpoint/balancing/physical) API endpoint is often either slow to respond, or returns a 500 after a long time.

## Steps to Reproduce
1. Visit https://bmrs.elexon.co.uk/api-documentation/endpoint/balancing/physical and click "Try it out"
2. In the `bmUnit` field, enter `2__HFLEX001`
3. In the `from` field, enter `2023-05-10T00:00Z`
4. In the `to` field, enter `2023-05-10T17:00Z`
5. Delete all datasets from the `dataset` query param
6. Click Execute, and wait for the response to come back

## Expected behaviour
A HTTP 200 response comes back in a timely manner (within a couple of seconds) with the requested physical data

## Observed behaviour
After 30 seconds, a HTTP 500 response is returned

## Screenshots
Full screenshot of request setup and response:
![image](https://github.com/elexon-data/insights-issues/assets/41060927/905b6c31-5317-4a1b-b95b-523c8e2c274f)
Screen snippet of timings:
![image](https://github.com/elexon-data/insights-issues/assets/41060927/76815a6f-9fdc-40c5-9836-ac076888e69b)
Screen snippet of network tab's request details
![image](https://github.com/elexon-data/insights-issues/assets/41060927/ced286a2-4529-4887-a67c-ff68caae33e9)

## HTTP requests/responses
The full HTTP request is as follows:
```
GET /bmrs/api/v1/balancing/physical?bmUnit=2__HFLEX001&from=2023-05-10T00%3A00Z&to=2023-05-10T17%3A00Z HTTP/1.1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Host: data.elexon.co.uk
Origin: https://bmrs.elexon.co.uk
Referer: https://bmrs.elexon.co.uk/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
accept: text/plain
sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```
Full HTTP response headers:
```
HTTP/1.1 500 Internal Server Error
Date: Wed, 10 May 2023 15:09:40 GMT
Content-Type: application/problem+json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache,no-store
Pragma: no-cache
Expires: -1
Strict-Transport-Security: max-age=31536000
Access-Control-Allow-Origin: *
```
and with body
```json
{
   "type":"https://tools.ietf.org/html/rfc7231#section-6.6.1",
   "title":"An error occurred while processing your request.",
   "status":500,
   "traceId":"00-7436184923cc2c5dbd2035dc79d98a71-6dff49be6f9dba50-00"
}
```

## Additional context
This is not specific to these query params. The endpoint will often return a 500 or take a long time (tens of seconds) to respond with different values for the BMU, the time range, and the datasets requested.

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by beccar97** [comment]
As part of our ongoing performance improvements work we have made several improvements to this endpoint, and are no longer seeing this issue. The average response time in July was just over a second and we no longer see high levels of 500 type response for this endpoint.
