### ISSUE TITLE
DISEBSP

### ISSUE THREAD

**Issue by Yoxy67** [elexon-data/insights-issues#24]
Hi 

We are interested in the below dataset:

Settlement system prices by settlement date (DISEBSP) (PREVIEW)

Returns settlement system buy and sell prices generated by the SAA for a given settlement day, relating to the data for a settlement run.

A couple of questions:

1. When will this be live?
2. Will this data include SAA updates as the current BMRA (DERSYSDATA) does not, it would be good to not have to use the Bestview prices file on the ELEXON portal site to get ii,sf r1, etc updates.  Would you also add a flag to show which update it is I.e R3

Thanks in advance
Phil

**Comment by zghanty** [comment]
Hi - We are doing some further testing before changing the feature flag on our prod where you will be able to access. We expect this shortly after 31 Jan . 
Initially we will do the indicative calcs after the SP and the next day we will perform a D+1 refresh. Later in the year we will look at refreshing with Settlement run types.
