### ISSUE TITLE
Inconsistant Date format - Datasets - Metadata Latest - Datetime format issue

### ISSUE THREAD

**Issue by pyoxall67** [elexon-data/insights-issues#25]
Datasets - Metadata Latest
[API documentation | Insights Solution (elexon.co.uk)](https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/metadata/latest)
According to API main documentation datetime should be written using RFC3339  format. 
Also, in bottom section of attachment, date time example is written using RFC3339 format, with 3 places for second fragments and ending with Z mark.

But when testing the API or calling the API datetime format returned doesn't have the  Z mark.
Which Time zone is used for this report and which time format is applicable for it?
![pic1](https://github.com/elexon-data/insights-issues/assets/12989501/afcdcb3a-66f7-4274-8fda-e1a0fd48c094)

**Comment by beccar97** [comment]
This has now been fixed, and results returned from this endpoint are correctly formatted using RFC3339 and showing the UTC timezone
