### ISSUE TITLE
"This website uses cookies" banner breaking on Safari

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [elexon-data/insights-issues#27]
## Describe the issue
The "This website uses cookies" banner on [the elexon website](https://www.elexon.co.uk) does not display on Safari, so the website appears grey and non-functional.

Safari:
<img width="949" alt="Screenshot 2024-02-28 at 16 59 39" src="https://github.com/elexon-data/insights-issues/assets/24707398/0c5c81c9-36c1-425b-8211-31a9e73a0873">

Chrome:
<img width="997" alt="Screenshot 2024-02-28 at 17 00 31" src="https://github.com/elexon-data/insights-issues/assets/24707398/a888f440-ef6c-484f-b359-3bbecfe96dc8">

**Comment by Kim-Balmer** [comment]
HI Marcin.  As you query is not specifically related to the Insights application can I ask you  to submit the enquiry to Elexon Support (https://support.elexon.co.uk/csm). The correct team will be able to respond directly about what you are experiencing and what device you are using.  Many Thanks

**Comment by MarcinKonowalczyk** [comment]
will do. same for #28. closing both here 👍
