### ISSUE TITLE
"What's New" section breaking in Safari

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [elexon-data/insights-issues#28]
## Describe the issue

["What's New" section](https://bmrs.elexon.co.uk/whats-new) of the elexon website does not display correctly on Safari (see screenshots). Possibly related to #27.

Safari:

<img width="997" alt="Screenshot 2024-02-29 at 15 22 08" src="https://github.com/elexon-data/insights-issues/assets/24707398/67200162-d6cb-47cc-8c88-768ec0b32162">

Chrome:

<img width="997" alt="Screenshot 2024-02-29 at 15 22 13" src="https://github.com/elexon-data/insights-issues/assets/24707398/c45d8ea8-1c0c-4b21-9719-705cec224015">

**Comment by Kim-Balmer** [comment]
What version of Safari are you using please.
