### ISSUE TITLE
A few issues with the feeds

### ISSUE THREAD

**Issue by pyoxall67** [elexon-data/insights-issues#29]
1)
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/BOALF/stream
Inconsistent column name in API response and documentation: The column name in the example listed on this page is "nationalGridBmUnitId". API response returns column name "nationalGridBmUnit"

2) 
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/DCI/stream
Always returns an empty response, regardless of the params supplied.
for example
https://data.elexon.co.uk/bmrs/api/v1/datasets/DCI/stream?publishDateTimeFrom=2019-01-01T13:08:00Z&publishDateTimeto=2024-02-24T15:08:00Z
I would expect at least one record returned in the selected date range

3)
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/CCM/stream
"amount" returned is always 0

4) 
B1610 report, column halfHourEndTime
is not in Z format, missing Z at the end even in docs and example it is listed with Z format
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/B1610/stream
[data.elexon.co.uk/bmrs/api/v1/datasets/B1610/stream?from=2024-02-13&to=2024-02-14&settlementPeriodFrom=1&settlementPeriodTo=50](https://data.elexon.co.uk/bmrs/api/v1/datasets/B1610/stream?from=2024-02-13&to=2024-02-13&settlementPeriodFrom=1&settlementPeriodTo=50)

5) Inconsistent date/time format in API response and example value supplied on page
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/OCNMF3Y2/stream
API response has datetime format without second fragments, while the example value supplied has second fragments.

6) 
When can we expect APIs marked with PREVIEW to have some data? Can we expect it by 31.03.2024?
for example: 
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/AOBE/stream - AOBE
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/BEB/stream - BEB
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/CBS/stream - CBS
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/PBC/stream - PBC

Thanks In Advance

**Comment by pyoxall67** [comment]
any feedback would be welcomed

**Comment by caligoig** [comment]
Same issue here. Can you please provide some feedback here? Thank you

**Comment by Kim-Balmer** [comment]
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/BOALF/stream
Inconsistent column name in API response and documentation: The column name in the example listed on this page is "nationalGridBmUnitId". API response returns column name "nationalGridBmUnit"

**Could you provide an example please, I can only see BMUnit is shown in the BOALF datasets.**

https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/DCI/stream
Always returns an empty response, regardless of the params supplied.
for example
https://data.elexon.co.uk/bmrs/api/v1/datasets/DCI/stream?publishDateTimeFrom=2019-01-01T13:08:00Z&publishDateTimeto=2024-02-24T15:08:00Z
I would expect at least one record returned in the selected date range

**I would expect to see the entry for 09/08/2019 output in the stream end point. I will investigate further.**
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/CCM/stream
"amount" returned is always 0

**Correct, this is the value currently being received.**
B1610 report, column halfHourEndTime

is not in Z format, missing Z at the end even in docs and example it is listed with Z format
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/B1610/stream
[data.elexon.co.uk/bmrs/api/v1/datasets/B1610/stream?from=2024-02-13&to=2024-02-14&settlementPeriodFrom=1&settlementPeriodTo=50](https://data.elexon.co.uk/bmrs/api/v1/datasets/B1610/stream?from=2024-02-13&to=2024-02-13&settlementPeriodFrom=1&settlementPeriodTo=50)

**Noted**

Inconsistent date/time format in API response and example value supplied on page
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/OCNMF3Y2/stream
API response has datetime format without second fragments, while the example value supplied has second fragments.

**Noted**

When can we expect APIs marked with PREVIEW to have some data? Can we expect it by 31.03.2024?
for example:
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/AOBE/stream - AOBE
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/BEB/stream - BEB
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/CBS/stream - CBS
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/PBC/stream - PBC

**Data should now be present.  ‘Preview’ label will be removed.**

**Comment by Kim-Balmer** [comment]
https://data.elexon.co.uk/bmrs/api/v1/datasets/DCI/stream?publishDateTimeFrom=2019-01-01T13:08:00Z&publishDateTimeto=2024-02-24T15:08:00Z
I would expect at least one record returned in the selected date range

I would expect to see the entry for 09/08/2019 output in the stream end point. I will investigate further.

**This has been resolved and all received DCI notifications are present which at time of writing is just the 09/08/19**
