### ISSUE TITLE
Settlement system prices by settlement date (DISEBSP)

### ISSUE THREAD

**Issue by pyoxall67** [elexon-data/insights-issues#30]
This dataset only has history back to the 31 jan 2024, is this an error?  There is another dataset :Market depth by settlement date (IMBALNGC, BOD, DISEBSP, DISPTAV)  that is also missing this data

![Screenshot 2024-03-19 182819](https://github.com/elexon-data/insights-issues/assets/12989501/c8558bdc-48cb-437e-a0b6-4d5b41ab70e8)

**Comment by Kim-Balmer** [comment]
Good Morning,  Yes that date is correct.  The Indicative Settlement Calculation is now calculated via SAA (Settlement Allocation Agent) and received into Insights.  As this is a new calculation there is no historic data available.  There is an item on our backlog to review this post Go Live and look to backfill values.  At present data prior to this points is still available in the legacy BMRS
