### ISSUE TITLE
Data gap in DAG/stream, missing data for publish date 2024-04-09

### ISSUE THREAD

**Issue by caligoig** [elexon-data/insights-issues#32]
## Describe the issue
Data Gap in DAG/stream API Request. No data published on 2024-04-09, making a day range gap for settlement date 2024-09-10 settlement periods 3 to 48 and 2024-09-11 settlement periods 1-2

## Steps to Reproduce
1. Go to [https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/DAG/stream](https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/DAG/stream)
2. Set filters with these values publishDateTimeFrom "2024-04-09" publishDateTimeTo "2024-04-10"
3. Click Execute
4. Return empty result set

## Expected behaviour
No data is returned and I expect it should return data for settlement date 2024-09-10 settlement periods 3 to 48 and 2024-09-11 settlement periods 1-2.

## Observed behaviour
No data is returned for filter values publishDateTimeFrom "2024-04-09" publishDateTimeTo "2024-04-10"

## HTTP requests/responses
To make API call where you can see this issue go to [https://data.elexon.co.uk/bmrs/api/v1/datasets/DAG/stream?publishDateTimeFrom=2024-04-09&publishDateTimeTo=2024-04-10](https://data.elexon.co.uk/bmrs/api/v1/datasets/DAG/stream?publishDateTimeFrom=2024-04-09&publishDateTimeTo=2024-04-10)
No data is returned and I expect it should return data for settlement date 2024-09-10 settlement periods 3 to 48 and 2024-09-11 settlement periods 1-2.

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by Kim-Balmer** [comment]
Thank you for your post. I can confirm that data was not received from source and we are investigating further.
