### ISSUE TITLE
Multiple gaps in historic data for FREQ/stream

### ISSUE THREAD

**Issue by caligoig** [elexon-data/insights-issues#33]
## Describe the issue
Multiple gaps in historic data for FREQ/stream. 

## Steps to Reproduce
1. Open the FREQ_Gaps.csv file attached
2. Column A is "Last measurementTime before the gap"
3. Column B is "Following measurementTime after the gap"
4. Column C is gap duration in seconds
5. Column D is number of missing frequency entries
6. Click on column E's link, that will show link where the gap is found

## Expected behaviour
Expected is to see frequency data every 15 seconds.

## Observed behaviour
Data is missing for specified time intervals.

## HTTP requests/responses
All of the API requests are listed in FREQ_Gaps.csv E column. You can use any of them to see the gap.

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

[FREQ_Gaps.csv](https://github.com/elexon-data/insights-issues/files/15000885/FREQ_Gaps.csv)

**Comment by Kim-Balmer** [comment]
Thank you for your enquiry, this is being investigated.
Please do contact [insightssupport@elexon.co.uk](mailto:insightssupport@elexon.co.uk) further further support

**Comment by Kim-Balmer** [comment]
Source files were not submitted by the Provider, no further action.
