### ISSUE TITLE
Multiple gaps in data for DATL/stream

### ISSUE THREAD

**Issue by caligoig** [elexon-data/insights-issues#34]
## Describe the issue
Multiple gaps in data for DATL/stream.

## Steps to Reproduce
1. Open the DATL_Gaps.csv file attached
2. Column A is "Last startTime before the gap"
3. Column B is "Following startTime after the gap"
4. Column C is gap duration in seconds
5. Column D is number of expected missing entries
6. Column E is missing settlementDate
8. Click on column F's link, that will show link where the gap is found

## Expected behaviour
Expected is to see data for every settlement period (startTime every 30 minutes) for links listed in column E.

## Observed behaviour
Data is missing for specified time intervals.

## HTTP requests/responses
All of the API requests are listed in DATL_Gaps.csv E column. You can use any of them to see the gap.

## Checks
Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

[DATL_Gaps.csv](https://github.com/elexon-data/insights-issues/files/15002538/DATL_Gaps.csv)

**Comment by Kim-Balmer** [comment]
Thank you for your enquiry, this is being investigated.
Please do contact [insightssupport@elexon.co.uk](mailto:insightssupport@elexon.co.uk) further further support

**Comment by Kim-Balmer** [comment]
Source data was nor received from the provider, no further action to be taken.  Insights is presented a full set of data as received.
