### ISSUE TITLE
Possible data gap for 2024-03-14T10:00:00Z in DISPTAV

### ISSUE THREAD

**Issue by caligoig** [elexon-data/insights-issues#37]
## Describe the issue
A time 2024-03-14T10:00:00Z data is missing from ["Indicative volumes by settlement date (DISPTAV)"](https://bmrs.elexon.co.uk/api-documentation/endpoint/balancing/settlement/indicative/volumes/all/%7BbidOffer%7D/%7BsettlementDate%7D) and ["Indicative volumes by settlement period (DISPTAV)"](https://bmrs.elexon.co.uk/api-documentation/endpoint/balancing/settlement/indicative/volumes/all/%7BbidOffer%7D/%7BsettlementDate%7D/%7BsettlementPeriod%7D) report, settlementPeriod=21

## Steps to Reproduce
1. Go to https://bmrs.elexon.co.uk/api-documentation/endpoint/balancing/settlement/indicative/volumes/all/%7BbidOffer%7D/%7BsettlementDate%7D
2. Fields: "settlementDate" = "2024-03-14", "bidOffer" = "bid" (or "bidOffer" = "offer", data is missing for both values)
3. Click Execute
4. In data returned look for 2024-03-14T10:00:00Z. Data is missing for 2024-03-14T10:00:00Z settlementPeriod 21

## Expected behaviour
I expect there should be at least one record for either bid or offer for 2024-03-14T10:00:00Z settlementPeriod 21

## HTTP requests/responses
https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/indicative/volumes/all/bid/2024-03-14
https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/indicative/volumes/all/offer/2024-03-14
https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/indicative/volumes/all/bid/2024-03-14/21
https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/indicative/volumes/all/offer/2024-03-14/21

## Additional context
I think this is related to https://github.com/elexon-data/insights-issues/issues/35 and https://github.com/elexon-data/insights-issues/issues/36

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by Kim-Balmer** [comment]
At present this is a genuine gap in data which is being investigated.
