### ISSUE TITLE
Incomplete backfilling of historical data

### ISSUE THREAD

**Issue by trader-short** [elexon-data/insights-issues#43]
## Describe the issue
The historical data still isn't completely available for some endpoints. If we query PN data before 2018-03-01, it returns an empty data response. MELS,MILS, BOD are working fine. TSDF, NDF don't have data before 2021-06-28. Is the historical data backfilling process still ongoing?

## Steps to Reproduce
1. Go to  /endpoint/datasets/PN or TSDF endpoint
2. Query data for the mentioned data
3. There will be an empty data response

## Expected behaviour
Should return  the requested historical data

## Observed behaviour
No data

## Screenshots
PN data not available for 2018-03-01 and before
![PN_datapng](https://github.com/user-attachments/assets/960ba37d-e923-4bed-85c9-e30118d5255a)

TSDF data not available for 2021-06-28 and before
![tsdf_data](https://github.com/user-attachments/assets/f372da7d-3efe-41ec-9064-611103260965)

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by Kim-Balmer** [comment]
I can confirm that a data from the legacy system has been migrated.
PN data goes back to 2016,
Some data sets do go back to 2021/2022 but historial data is available via the Elexon Portal.
