### ISSUE TITLE
FUELHH and other outturn reports do not include solar data

### ISSUE THREAD

**Issue by Samreay** [elexon-data/insights-issues#6]
## Describe the issue
Using the BMRS, we were able to get a proper breakdown of generation outturn using the B1620 report. The report gave us data including wind onshore, wind offshore, and solar. Using either the new generation summary report or the FUELHH report, wind is aggregated (not an issue), but solar is a fuel type.

This is confirmed in the fuel type references endpoint, that solar is not its own category.

## Steps to Reproduce
1. Go to https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/FUELHH/stream
2. Make request hoping for solar data
3. Be sad

## Expected behaviour

@zghanty raising this now to feed into the battery as a fuel type discussion for Elexon, but it would be great if solar could be a fuel type as well. Feels like its about time to try to push for some better change on this one as well.

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by zghanty** [comment]
@Samreay : Thanks for raising this. The inclusion of new Fuel Type categories will need to be made the upstream source data governed by  BSC. We will liaise with NGESO to get the ball rolling on the BSC change proposal.

**Comment by zghanty** [comment]
@Samreay - We've started discussion to get the change proposal for additional Fuel-Type category
