### ISSUE TITLE
Indicated Imbalance(IMBALNGC) definition change in API documentation

### ISSUE THREAD

**Issue by trader-short** [elexon-data/insights-issues#7]
## Describe the issue
Indicated Imbalance for a settlement period is defined as the difference between Indicated Generation(INDGEN) and National Demand Forecast(NDF) in the Insights API documentation. But the values returned are not consistent with this definition. Say for settlement period 16 today(25-05-2023), the Indicated Imbalance value returned is 812MW. INDGEN and NDF values for SP16 are 27571MW and 25428MW respectively, thus difference and apparently Indicated Imbalance will be 2143MW.  The 812MW value returned matches the difference between INDGEN(27571MW) and TSDF(26759MW), which also how Indicated Imbalance is defined in the Grid Code (BC1.A.2.2). I've attached the required screenshots.
## Steps to Reproduce
1. Go to https://data.elexon.co.uk/bmrs/api/v1/datasets/IMBALNGC/stream?boundary=N and check for the Indicated Imbalance for any recent SP(812MW for SP16 at that time)
2. Get INDGEN, NDF, and TSDF values for the same settlement period using the Insights API, or just check the BMRS day-ahead demand page for all the values.
3. Take the difference between INDGEN - NDF(27571 - 25428)
4. It doesn't match the value returned for Indicated Imbalance(812MW)

## Expected behaviour
If the definition in the Insights API documentation is corrected, Indicated Imbalance value returned should be 2143MW for SP16

## Observed behaviour
Actual value returned for IMBALNGC (812MW) is difference between INDGEN and TSDF
## Screenshots
![GRID_CODE_DEFINITION](https://github.com/elexon-data/insights-issues/assets/56205818/1c9cf88d-cd77-453a-882d-d2ac72b45190)

![bmrs_demand_page](https://github.com/elexon-data/insights-issues/assets/56205818/f8b056b3-a17a-41e2-b728-1d289e13e0b1)

![IMBALNGC_SP16](https://github.com/elexon-data/insights-issues/assets/56205818/c1e1c2cd-0b3c-4408-b2a9-9ba5758ea589)

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by zghanty** [comment]
Thanks @trader-short - We have lifted the definition from our glossary https://www.bmreports.com/bmrs/?q=help/glossary


![image](https://github.com/elexon-data/insights-issues/assets/118724250/8f0210fb-7677-42d6-8e82-663bce8ea60f)

We will reproduce this and fix as required

**Comment by jackiewoodburn-sw** [comment]
Hi @trader-short - thanks for flagging this! We've updated the documentation to reflect the amended definition.

**Comment by trader-short** [comment]
Thank you @jackiewoodburn-sw. The definition has been updated on the /datasets/IMBALNGC but on the /datasets/IMBALNGC/stream endpoint, the change is not revised yet. I've attached screenshots for both endpoints below

![Capture2](https://github.com/elexon-data/insights-issues/assets/56205818/d27a2841-85cc-42a5-9d6a-5d8ca673608d)

Instead of National Demand Forecast, it should be Transmission System Demand Forecast

![Capture1](https://github.com/elexon-data/insights-issues/assets/56205818/6ef6f5b3-4ebd-47e5-b1fc-f4687e23a154)
