### ISSUE TITLE
Possible discrepancies in bid-offer data

### ISSUE THREAD

**Issue by trader-short** [elexon-data/insights-issues#9]
## Describe the issue
For 03.06.2023 settlement period 28, bid-offer data submitted by T_BHLAW-1 BM unit has 1000MW offer volume at -£35 while the Maximum Export Limit(MEL) for this BM unit is 108MW. How is it possible for a BMU to offer to increase its generation in excess of its generating capacity?  Some BMUs do submit excess volumes but in such cases, the offer prices are over VoLL(Value of Lost Load at £5000), thus effectively nullifying the chances of these offers getting accepted.

In this case, take note of the negative price at which the volume is offered. In cases when the grid has a lot of surplus energy with negative imbalance prices, offers submitted at -ve prices are observed. But the SP28 had a positive net imbalance volume(NIV) of 239MWh.

## Steps to Reproduce
1. Go to https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/BOD/stream
2. Get the data for the following parameters: {'from': '2023-06-03', 'to': '2023-06-03', 'settlementPeriodFrom': 28, 'settlementPeriodTo': 28, 'bmUnit': 'T_BHLAW-1' }
3. Check the offer volume(pairID=1) and price (1000MW at -£35)
4. Check the MEL for T_BHLAW-1

## Expected behaviour
In an ideal scenario, the volume offered by a BM unit in a settlement period would be less than its maximum export limit(MEL)

## Observed behaviour
1000MW of offer volume at -£35.

## Additional Information
Same pattern was observed for the following BM units: T_DUNGW-1, T_GORDW-1, T_GRIFW-1, T_GRIFW-2, T_STLGW-1, T_STLGW-2, T_STLGW-3, T_TDBNW-1.  They had offered volumes(800-1000MW) which are in excess of MEL and offered at a price of -£35. Almost all of these are wind farms based in Scotland. 

Is this a result of invalid submissions by the BM units themselves or did some error get picked up during the validation and processing?

## Screenshots
![bod_T_BHLAW](https://github.com/elexon-data/insights-issues/assets/56205818/c4ca4169-3cd6-4ba8-b373-9f92c462b4f2)

## Checks

Please answer the following questions for yourself before submitting an issue.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository
- [x] I'm reporting a problem and not a feature request
- [x] I have added the correct labels
- [x] I have added screenshots or other relevant evidence (if applicable)

**Comment by zghanty** [comment]
@trader-short - Hi I have looked at this , the platform is correctly processing the data but the question you raised is valid. I will have to ask NGESO for clarification as you would expect this to be close to MEL.  
I've flag this as 'won't fix' as it is not an issue with Insights Platform but a data issue that needs further investigation

**Comment by trader-short** [comment]
Thanks for the update @zghanty. Just to add some more information, all these BM units have changed their offer prices to £1500 from settlement period 4 of 13.04.2023, which is what they used to offer at before. Offering 1000MW at £1500 makes for better reasoning than at -£35, which was observed in the last week since the probability of these offers getting accepted becomes minimal.
![bod_T_BHLAW-1](https://github.com/elexon-data/insights-issues/assets/56205818/05db23e3-8a6b-4010-b54d-846464ca7f2b)
